### ISSUE TITLE
add option to use real floor height

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#102]

**Comment by BernieBI** [comment]
agree, it would be a nice function

**Comment by CarlKenner** [comment]
Fixed, but it's not quite right, and I can't work out why. The chaperone is slightly above the virtual floor.

**Comment by KozGit** [comment]
In idPlayer::GetViewPosVR, there is a 5 inch offset added to the view height.  This was put in place because the armor/player body is so tall it blocks the view if it's not included when using the default view height. If you drop the view height in the menu by 5 inches ( from your real world view height ) , I bet the chaperone lines up perfectly.

1st easy fix is to add this offset to the value displayed in the viewheight menu ( display the effective value ) , that way it makes more sense.  

Changing the view height when viewing the player body is an issue - the view origin can drop into the model and it looks terrible. I need to figure out the best way to scale the player model when the view height is changed.  I can't just scale the model matrix, because that will break the joint calculations and collision + hit detection for the player ( warnings in the code not to do this. ) 

I'm thinking I may split the difference of the delta between the adjusted view height and the default view height, and try to apply it when the leg IK is computed.  Kind of like when ducking the knees bend, but instead  adjust the chest joint so the torso shrinks a little vertically, same with the hips.  

I also think it might make sense to scale the view height when vr_scale is changed.

I would like the vr_useFloorHeight to default to 0 - when it's enabled, for me it totally breaks switching between standing and seated play, which I do frequently when developing.  I think this is a fairly big change to the way position is calculated, and I think it should be opt-in for established users.  It's a great option,  I just don't want  to confuse existing players when the tracking behavior changes.  ( The first time I played with this option, I didn't know you had added it, and thought I had messed up my rift tracking.  Yes, I'm an idiot.)

**Comment by CarlKenner** [comment]
Sorry, I'll change the default back.

You are changing the lengths of the arms somehow. I don't know if you can do that to the torso or legs too.
But for now our huge space marine just bends his legs to duck down when using the floor height, if you're not that tall.
It doesn't break seating/standing play, unless your chair is low enough to count as crouching, in which case you can't jump. It works as intended... you are seated height in-game and the floor is in the right spot. Which personally I like when playing seated, but they can easily change it in the menu.
It might break the motion-triggered crouch though. I forgot about that option, now that it's off by default. 
Dropping the view height in the menu should have no effect in floor height mode. I'll just subtract a constant 5".

**Comment by KozGit** [comment]
No need to apologize!

I already updated the default, and added code to switch the oculus tracking origin between seated and standing when the option is changed. ( Otherwise when it's enabled, the some of the tracked screens, like the legal splash and the loading screens, are too low.)

**Comment by CarlKenner** [comment]
That 5 inches is from some really old code that I added back in DK1 days, back when this was tmek's mod. DK1 didn't have any positional tracking, and I was crudely trying to make the head stay close to the neck in the player model, which was hard because the player model moved differently depending on what weapon I was using, so I was adjusting the head-neck model.

At some point we're going to have to review some of the really old code and see if it still makes sense. Because this function looks weird to me. We also need to document some of our tracking variables better so it's clear exactly what they're relative to.

**Comment by CarlKenner** [comment]
Fixed crouching when using floor height while seated. This mode is all fixed now.

**Comment by CarlKenner** [comment]
Fixed crouching when using floor height while seated. This mode is all fixed now.
