### ISSUE TITLE
Turn off movement of character using touchpad

### ISSUE THREAD

**Issue by keironwaites** [KozGit/DOOM-3-BFG-VR#114]
I would like to teleport everywhere. However, the same button that allows teleportation also moves the player model around on touch. This is causing my player to run around when I don't want him to as I naturally touch the touchpad before tapping it. I just want to teleport.

I don't see this being a problem in the YouTube video so is this a bug or a setting I have missed?

Thanks.

**Comment by keironwaites** [comment]
On further investigation I've found that the touchpad up/down/left/right touch was assigned to movement. I have turned these off.

Please note that I had changed my controls to left-handed. Perhaps when doing this the up/down/left/right touchpad touches should me moved to the right?

**Comment by CarlKenner** [comment]
> I would like to teleport everywhere.
That's impossible for now. You can't teleport up and down ladders, across gaps you need to jump across, across some thresholds, or to some outdoors areas. That's due to bugs in the teleportation code. You probably need at least move forwards to be mapped to something.

> Please note that I had changed my controls to left-handed. Perhaps when doing this the up/down/left/right touchpad touches should me moved to the right?

There's a console variable for that. I thought most people would be used to left stick movement, even if left handed, so it's not the default:
`vr_handSwapsAnalogs 1`

**Comment by KozGit** [comment]
Closing issue, as it seems to have been addressed, and no further responses received in four days.
