### ISSUE TITLE
Doom 3 bfg Vr will not start on dual monitor setup (with Solution

### ISSUE THREAD

**Issue by Liquidspark** [KozGit/DOOM-3-BFG-VR#142]
When I downloaded this mod, I was exited until it would not start. After spending some time in the vr_oculus_default.cfg I found the issue the game was trying to start up in between both of my monitors. I adjusted the setting "set r_windowX" "-350"" to "set r_windowX" "0", and viola the game booted up with no further issues, I just wanted to let you guys know and maybe the dev can make a fix for this. Just in case you wanted to boot up this awesome mod. Thanks again!

**Comment by CarlKenner** [comment]
Unfortunately, I no longer have dual monitors, since my 58" 3D TV didn't survive a Vive session playing Budget Cuts. So I can't test.

**Comment by Liquidspark** [comment]
Haha, That's a shame

**Comment by KozGit** [comment]
I think this is probably my fault.  I must have moved the active window partway off of my screen when testing, and then saved that position in the default config file for the rift.  I just edited the default configs for the rift and vive to make sure the startup window position is near bottom left of the main screen, so with the next release this wont be an issue.

Sorry for the issue and thanks for the headsup.

( I have a dual monitor setup, but my 2nd monitor is to the right, so it was not trying to span two windows )

Just out of curiosity, what gfx card are you using, and what's your monitor config like?

**Comment by Liquidspark** [comment]
No Problem, I'm just glad it was an easy fix. My setup is as follows :
Cpu: Intel i7 6700k @4.5ghz
Ram: 16GB Corsair Dominator Platinum 3000mhz
Graphics: 2x Asus 980ti strix @1500mhz core
Monitor setup: Main: acer 27" 1080p 144hz xb270h "In front of me of course"
Secondary:"to the left of the main monitor" acer 23" 1080p 60hz s231hl
If you have any other questions feel free to let me know.

**Comment by Liquidspark** [comment]
Also, I have noticed that audio does not play through external headphones, unless I have the rift software in audio mirroring mode or if I'm using the rift headphones which I rarely do. Haven't been able to determine a fix on that though.

**Comment by KozGit** [comment]
If you are using a rift, and want to use external speakers or headphones instead of the rift headphones, open the console ( press ~ to open console ) and type vr_forceOculusAudio 0 <enter>.  By default, if using a Rift, the game searches for and selects the Rift audio device as the audio output.  You will need to restart the game after changing this value. If you set this to 0 and are using a rift, the game will use whatever audio device is set as the windows default device. If you don't want to use the windows default device, follow the instructions below to manually select an audio device.

If using OpenVR, when the game launches it will select whatever audio device is set as the windows default.
If you want to change this:

From the console ( ~ in game to open console ) , type listDevices  < enter > this will list all detected audio playback devices. Take note of the number of the audio device you want to use.

Then set cvar s_device to select an audio device from this list. You will need to restart the game after changing the audio device.

**Comment by Liquidspark** [comment]
Thank you, that has cleared up that issue
