### ISSUE TITLE
How do I install the latest mod and update from a previous one?

### ISSUE THREAD

**Issue by lghtanddrk** [KozGit/DOOM-3-BFG-VR#153]
I haven't touched Doom since I installed the mod and hi-res texture pack to play with my Vive at the end of November.

I just read some of the changes that have been done since then - incredible!

Can you please tell me or point me to a step by step for updating to the latest version of the mod with hi-res texture packs given the fact I am working on a version from last year?

I want to point out too that I don't have the game installed on my C drive.

Thanks so much for your hard work!!

**Comment by WKGBPrewitt** [comment]
I'm not part of the team, but I'd say a fresh install is in order.  If I were you, since the save games don't carry over, I would uninstall the game from my computer, and delete the whole sub-directory.  Secondly I'd say follow this [tutorial.](https://www.reddit.com/r/oculus/comments/63wup0/complete_doom_3_vr_install_menus_features_guide/)  It's as easy as that.

**Comment by KozGit** [comment]
Download and run the installer on the releases page.  It will install a new .exe - just run that.

Note that there may be some issues with save games with the previous versions.

**Comment by KozGit** [comment]
If you're still having trouble, please let me know - hopefully its working now as there hasn't been a response in a few days.  Closing the issue for now, thx.
