### ISSUE TITLE
Game won't appear on my HMD or desktop.

### ISSUE THREAD

**Issue by OpticalSpinosaurus** [KozGit/DOOM-3-BFG-VR#162]
https://pastebin.com/4Pvu6Bvc

Here's the pastebin. I can hear audio. Any reason Doom VR won't work?

**Comment by KozGit** [comment]
This .exe should show some additional debugging info - you will need to create a shortcut and edit it to enable logging just like before.  Post another pastebin of the log output.

[Doom3BFGVR_ErrorDebug.zip](https://github.com/KozGit/DOOM-3-BFG-VR/files/1033244/Doom3BFGVR_ErrorDebug.zip)

**Comment by KozGit** [comment]
The problem is an issue with the way the oculus runtime/SDK handles multiple video cards.

ovr_CreateTextureSwapChainGL will fail with no specific error message if multiple video cards are installed and the rift is not attached to the primary card.  The issue can be worked around by moving the rift to the primary video card - it will be up to oculus to implement a software fix.
