### ISSUE TITLE
Bug: Left hand disappears, right hand is fixed (won't move)

### ISSUE THREAD

**Issue by mnmean** [KozGit/DOOM-3-BFG-VR#167]
This issue cropped up in Alpha Labs 4, I believe, in the section where you have to choose between a bridge or something else (probably known to Fully Possessed players "as that part where you have to run and jump over the gap because AAS doesn't extend over the gap".) Things that may have preceded the bug: editing the settings file in-game (I don't think I ultimately made any changes), and a hard shut down (via steamvr shutdown or other method). The bug occurred in the DOOM3BFGVR_AMD_TEST2.exe, which I play to avoid the startup menu bug, but continues in the regular .exe. 

Description of problem: When loaded (any previous save), the right hand will stay in a rigid position and not move, regardless of controller position. The left hand will simply lot appear at all. The left hand will appear and the right (weapon) hand will begin to respond appropriately relative to wand position IF a button is pressed (right trigger (fire), right track pad (teleport, switch weapons), left track pad move. Buttons that do NOT effect the neutral position: left grip (crouch), left pad click (flashlight), right grip (reload).  Sometimes the proper positioning is stable, other times it flickers between the right position and the neutral position. 

Stuff I've tried: 
deleting the .cfg files for controls (doom3/fully possessed/) (they did not reappear after starting the game again with either TEST_2 or regular.exe). 
Trying previous saves. 
Running the install file again.
Deleting /fully possessed/ and running install again. 

Other games check out fine. 

Specs: i5 4690, AMD R9 390, Vive, SteamVR beta.

**Comment by KozGit** [comment]
So, from your description, it looks like you may have delete the default config files from the actual game install directory - you probably want to try to put those back.  (They are the files copied to the save game directory then modified to reflect your current config. If they are missing, and the save game directory is deleted, no VR controls will be bound at all the next time you launch)

If you get those configs re-installed, you can try deleting the configs from the save game directory, which is normally c:\users\(your user name here)\saved games\id software\doom 3 bfg\fully possessed\vr_*****.cfg

It looks like the game thinks there is a standard gamepad controller attached, and thinks you are trying to use that instead of motion controls.  

Try this to disable auto controller switching and to make sure the game is set to motion controls:

From the console ( press '~' in game to open the console ) type:

vr_autoSwitchControllers 0   (thats a zero) then press enter.
vr_controllerStandard 0 (thats a zero) then press enter.

Press '~' again to close the console.  You'll want to restart the game after making these changes.

Let me know if this resolves your issue.

**Comment by mnmean** [comment]
Restoring the config files didn't fix it, but the console commands did give me my hands back. Thanks!
