### ISSUE TITLE
Random changing weapon

### ISSUE THREAD

**Issue by kaeloth** [KozGit/DOOM-3-BFG-VR#209]
Hey all,

I've installed the mod but find myself randomly changing weapon, I'm not sure what's causing it.

I've tried swapping from the right to the left stick but still the same happens.

I've even unbound every key to change weapon except the voice option and the R_TOUCHPAD, yet it still happens.

I'm using the Oculus Rift and Touch controllers.

Any insight?

**Comment by KozGit** [comment]
Most often, this is the microphone in the Rift picking up background audio which is misinterpreted by speech recognition as a command to switch weapons.  ( By any chance, does it seem to switch to fists frequently?  The microphone can actually pick up audio from the rift headphones, sometimes the door hiss sounds can trigger the fists.  You can try a few things - turning down the microphone sensitivity in windows ( right click speaker icon in system tray, select recording devices, clink on 'microphone rift audio' then properties, then levels, then reduce the slider. Or you can do it thru Oculus Home, from the desktop click the gear at the top of the home window, click devices, click the picture of the Rift, then under 'Audio Input for VR' change the slider. ) 

You can also change the phrase that needs to be recognized to switch a weapon - look in the 'voice.dict' file in the 'dict' directory in the Fully Possessed directory, which is in the Doom 3 BFG directory.  Edit the action for the weapon that is being misrecognized - for example under to change what is recognized for 'fist',  look for an action with the name FIST, then modify the entries, for example change it to "weapon fist" instead of just "fist" ( this is actually done by default in the upcoming release)

You can also try completely disabling voice commands temporarily to verify this is the source of the problem - if not please let me know!

**Comment by kaeloth** [comment]
Hey,

Thanks a lot for your help, that seems to have fixed it!
