### ISSUE TITLE
Frame-rate is poor.

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#27]

**Comment by KozGit** [comment]
Some things I know need to be addressed:

Need to revisit materials for player body and weapons to check shadowing is optimal. ( noselfshadow)

Current rendering is render to buffer instead of render to texture, can save several full blits per frame by switching to render to texture.

GuiTrace code use to check traces against the PDA is creating several animation frame to check joint locations, need to optomize.

**Comment by CarlKenner** [comment]
The teleportation code I added is also tracing your path to the aim point every frame, which probably isn't necessary.
