### ISSUE TITLE
Graphical bug in first level, analog turn sensitivity, other minor issues and ideas.

### ISSUE THREAD

**Issue by ZachFett** [KozGit/DOOM-3-BFG-VR#270]
Hey there! I know you're working hard on releasing 0.22 but I wanted to throw a few bugs at you that I ran into tonight.

- There's a graphical bug in the first level, around where the break room is. I've attached a screenshot, it's that vertical black line. It's not in the base game as far as I can tell.

- Is there a way to lower the sensitivity when using analog turn? At the moment it is *very* fast. I tried changing mouse sensitivity in hopes of that working, but no luck.

- Any chance we could get the option to remove the watch on our character's wrist, since I'd prefer to just use the ammo counter hud when looking down? If not, not a big deal!

- Another minor cosmetic request I have, not a big deal if this can't happen, but how about instead of having the PDA bring up this hologram-like menu, we still get to use the actual PDA model and screen? Is that possible, or is there no way to "project" the menu onto that model?

- I haven't had any luck with getting my character height to save. It keeps resetting to 68 after every level load. Any ideas?

- Lastly, I would prefer to play with the character model turned on (full body/arms/etc.) however if I move forward it really glitches through my view. I had an idea on how to fix that however. Would we be able to control how far forward our view is? Like, if the view was just a few inches forward I think it'd possibly fix this issue so we can look straight down and not have our chest clipping through our view.

Thanks for reading through this, and thanks for putting so much time into this mod! You've been doing a fantastic job!

![20180624043612_1](https://user-images.githubusercontent.com/29797689/41819024-a2cb446e-776e-11e8-9588-ba12ff969135.jpg)
![20180624043630_1](https://user-images.githubusercontent.com/29797689/41819025-a52d6728-776e-11e8-965d-23a15c74b354.jpg)

**Comment by KozGit** [comment]
Hi, and thanks for the feedback:

> There's a graphical bug in the first level, around where the break room is. I've attached a screenshot, it's that vertical black line. It's not in the base game as far as I can tell.

This glitch exists in the base game - just to sanity check I launched BFG from steam and verified it's there.  Maybe one day I'll look at the map and see whats going on, but tbh it's a low priority at this point.

> Is there a way to lower the sensitivity when using analog turn? At the moment it is very fast. I tried changing mouse sensitivity in hopes of that working, but no luck.

You can change the turn speed from the console.  Press ~ to bring up the console, then use the joy_yawSpeed command.  Default is 240.  A higher value turns faster.  So to halve the turn speed you would type ' joy_yawSpeed 120' and press enter.

> Any chance we could get the option to remove the watch on our character's wrist, since I'd prefer to just use the ammo counter hud when looking down? If not, not a big deal!

not at this time, but the upcoming version improves the health and armor displays on the watch to make it a little more useful.  If you turn off the body and hands, you can use just the weapons with no watch.

> Another minor cosmetic request I have, not a big deal if this can't happen, but how about instead of having the PDA bring up this hologram-like menu, we still get to use the actual PDA model and screen? Is that possible, or is there no way to "project" the menu onto that model?

The issue here  is the low resolution of the rift/vive.  It's no problem to map the display directly on to the model, but the text is completely unreadable due to the low resolution. I actually tried this originally. I had to scale the model up to accomodate the resolution, but to be readable, it needed to be about the size of a large pizza box. This looked really odd, so I went with the hologram instead.  Once the resolution of HMD displays improves, it will be easy to change it back.

> I haven't had any luck with getting my character height to save. It keeps resetting to 68 after every level load. Any ideas?

This is a known issue with this version, and had already been fixed for the upcoming release.

> Lastly, I would prefer to play with the character model turned on (full body/arms/etc.) however if I move forward it really glitches through my view. I had an idea on how to fix that however. Would we be able to control how far forward our view is? Like, if the view was just a few inches forward I think it'd possibly fix this issue so we can look straight down and not have our chest clipping through our view.

This has also already been fixed in the upcoming release.  ( And the chest no longer surges forward when you walk/run ).

**Comment by ZachFett** [comment]
You're the best. Really glad to hear the character model will be fixed for the next update! That and the sensitivity thing were my only two major complaints, thanks for letting me know how to fix the latter!

And my bad, I had checked the original Doom 3 (I don't bother with BFG except for VR) and couldn't find that graphical bug.

Keep up the fantastic work!
