### ISSUE TITLE
Holster weapons on parts of your body

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#29]
It should be possible to look down and see your pistol hanging by your side, then pick it up (in either hand), use it, and put it back - like in Oculus Dead and Buried. The same with the other weapons on different parts of your body, and your PDA and flashlight.

**Comment by KozGit** [comment]
Can the player change weapon hands at will? If I grab the shotgun with my left hand and the machinegun with my right, should I be able to dual wield or limit to one active weapon?

**Comment by CarlKenner** [comment]
I don't know. I haven't implemented it yet, it's just a half-baked idea.

Also, should we be able to dual wield the flashlight with some of the weapons that are supposed to be two-handed?

Logically, we should be able to dual wield two pistols once we find a second one (I assume some enemies drop pistols, unlike Doom 1 and 2).

Doom-guy is known to be somewhat ambidextrous or left-handed, as he punches and fires the pistol with his left hand in Doom 1 and 2. Also his weapons in Doom 3 eject shells to the left.

Mars' gravity IRL is about a third of Earth's gravity (37.6%), but the guns are bulky and awkward, and still have the same inertia, and we're carrying a LOT of equipment.

Personally, I think it would be fun to wield two weapons at once, but it might be game-breaking in terms of how much damage you can do, and harder to implement.

But I'd like to be able to use either hand in a GUI.

**Comment by Codes4Fun** [comment]
I experimentally implemented this in my mod, but slots are not dynamic like in H3VR, the pda is fixed to your left leg and the holster fixed to your right leg. I also added two backpack slots, when activated will cycle the next/prev weapons.

https://github.com/Codes4Fun/RBDOOM-3-BFG/commit/1a59915703ea94471edabd601eb4573660440749

https://github.com/Codes4Fun/RBDOOM-3-BFG/commit/ef84aa7ab1d0dc1489793bc3a063930dd77983e0

https://github.com/Codes4Fun/RBDOOM-3-BFG/commit/3c14377a96f7561de7558ff06648d502736d7309

https://github.com/Codes4Fun/RBDOOM-3-BFG/commit/3132b60e99a4fbd4f9e4c564de1d6e4ba63293c3

Some other ideas... ammo on slots, and manually reloading, similar to H3VR and Onward. And instead of carrying a ridiculous amount of weapons, be able to only carry a few in holster slots, leaving the player to try and economize weapons and ammo. But then I started thinking, game wasn't designed for that, almost better to start working on a special designed game (total conversion mod) rather than try to change the experience of the original game.

**Comment by KozGit** [comment]
As bad as it sounds, I haven't had the chance to try any of the games that have implemented slots yet.  I agree that limiting the weapons the player can carry may change the game too much.  

This may have been tried before ( and may be what you were referring to ) but what about implementing something like virtual velcro?  Define a couple of places the player can stash the active weapon or grab a stashed weapon.  If there is already a weapon there, swap.  If the player wants a weapon not in a slot, they cycle thru inventory for it?

Mythbusters actually did an episode where they wanted to see if someone could carry all the weapons in Doom 3.  Don't want the player to look like this : 

https://pbs.twimg.com/media/B8uezq-CEAEKEL2.jpg
:)

I eventually want to implement manual reloading, but that will require revisiting the weapon models and anims.  There are some other things that we may want to do as well, like having the laser sight not originate from the barrel or add support for holding the weapons with both hands, which will also probably require revisiting the models - I'd just like to nail down everything we would like to do before breaking out blender again.

**Comment by CarlKenner** [comment]
The thing that annoyed me about that episode is they didn't even mention that Mars gravity is only 0.37 x Earth gravity, and Phobos and Deimos are ridiculously low gravity. Although gravity only affects lifting, not pulling them around horizontally.

**Comment by CarlKenner** [comment]
Fixed in pull request

**Comment by CarlKenner** [comment]
This is basically fixed. But I'd still like to:

- integrate the visible holsters into the inverse kinematics when showing your body
- fix the shadows in cutscenes
- make them visible in mirrors and cameras
- flip the pda when holstered on the other side
- swapping hands should affect teleport hand
- ideally, show them on the player model in cutscenes
