### ISSUE TITLE
Other less sickening locomotion options

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#31]
This is less important now that we have teleportation. But it would still be nice.

I'd like to see other locomotion options that are less sickening:

- ~~reduce FOV while virtually moving (Dolphin VR does this badly, Google Earth does this well)~~
- ~~show chaperone grid while virtually moving (it's a bit like a cockpit, but it doesn't help much)~~
- ~~black out screen while virtually moving (probably not great for moving around, but easy to implement and guaranteed not to make you sick)~~
- ~~third person while virtually moving (your view stays still, but your body moves out from under you while you are using the joystick, until you stop touching the stick, at which point your view teleports back to your body)~~
- virtually move in jumps (like comfort mode)
- floating objects in the air (dust?) that stay locked to the real world

**Comment by CarlKenner** [comment]
This is half fixed. Blacking out the screen works (mostly) and so does chaperone grid, and the two combined.

Reduced FOV, third person, jumps, and floating dust, are not implemented yet.

**Comment by CarlKenner** [comment]
This is mostly fixed. But I'm not happy with the stereo separation on the letterboxing or how Slow Mo affects the sound in Mars City 1.

**Comment by agamero** [comment]
Are you able to decouple the look from forward move direction? Maybe use the direction of the (movement) controller, or the average direction of both controllers as an option instead of the head direction, giving the option of looking one direction while shooting/moving another direction. This works well in a few other games, especially in outdoor areas. It might be a good fit here with comfort mode and FOV reduction/view clipping? Not sure since it is more corridor, but thought it would be good to bring it up in case it is possible and hasn't been considered. Thanks for awesome releases regardless!

**Comment by KozGit** [comment]
> Are you able to decouple the look from forward move direction?

I'm not sure if I'm answering your question or not, but currently, the view direction, the player body direction, and weapon aim are all independently controlled.  It's possible ( and very common )  to look one direction while moving another, and shooting somewhere else at the same time when using motion controllers.

**Comment by agamero** [comment]
I was actually running an older, different D3BFG VR build and thought it was the same so my comment was completely misplaced. How embarrassing! I have since tried out what your build and it is pretty awesome. Thanks for responding to my confusing message anyways and I will read through your build before commenting on anything else and maybe even have something to contribute at some point. Thanks for an awesome VR build for a classic (the original) romp through demons in hell on mars game!
