### ISSUE TITLE
Can I play seated with KBM?

### ISSUE THREAD

**Issue by lukeman3000** [KozGit/DOOM-3-BFG-VR#326]
I was wondering, can I sit at my computer and play this game in VR with KBM as I normally would? If so, is there any kind of of head tracking available?

**Comment by sycspysycspy** [comment]
No, you can't. Even if you can it's strongly not recommended, you would vomit a lot playing with keyboard and mouse. I believe I have tried some mod compatible with KBM on moddb, https://www.moddb.com/mods/doom-3-bfg-hi-def use it at your own risk.

**Comment by lukeman3000** [comment]
Interesting, it sounds as though you do not do well with seated experiences. Though I assure you, this is not the case with everyone. For example, you can play No Man’s Sky and The Forest seated. Also look at Mother VR. These are high profile games, not some one-off indie titles.  And there’s actually a lot of chatter in VR forums from people hoping to see more games follow in their footsteps (more seated support). You can even play classic Doom seated with KBM and it’s awesome.

When I first tried VR (back in Oculus DK2 days) literally the first week or so, I experienced slight vertigo. I never vomited (and the first experiences were really bad!) After that initial acclimation period it has not been a problem. Just saying, there are some of us (perhaps many) out there who would really, really enjoy being able to do this. Seated VR experiences are my favorite. I’m just casting my vote here but I would love to be able to play Doom 3 as normal with KBM, but seated with VR, and possibly with some implementation of head tracking (Half-Life 2 did a good job of this as well back when it had VR).

**Comment by KozGit** [comment]
Just curious, what headset are you trying to use?   And you should be able to rebind the controls to use KBM, but it's really ( really ) an inferior experience.

**Comment by lukeman3000** [comment]
I have a Valve Index. And just to be clear I haven't actually tried it yet, I was just wondering if this was possible.

**Comment by NPi2Loup** [comment]
I just test right now (with Valve Index)
It works, but in the first screen, when it say "press any button", you just need to wait a little.
You may rebind keyboard control and you must set control to "standard control" instead "motion control" in VR options, it's mandatory in order to control the weapons by KBM.
In this mode, the view is almost stable and only move by head movements, mouse aim the gun, and rotate view when your reach about 90°.
I found binding smooth rotate more usefull, don't know if it's possible to use mouse to rotate view like in notVR

But as Koz says, it a way better to play with motion controllers. Maybe for someone who can't stand for hours, it may be better.

How NMS plays seated ? how keyboard/mouse/view are managed ?

**Comment by KozGit** [comment]
Yes, if you have an Index, seated with motion controls is a vastly better experience.  Seated works well, you can recenter the view and / or adjust the character height so your character in game is at full height instead of seated if you wish.  I have a lot of seated time in the game from testing :)

**Comment by jdawgzim** [comment]
I play a lot of VR games on a swivel bar stool when I get tired.  I played 5 hour sessions in Skyrim VR that way.

**Comment by KozGit** [comment]
Closed, topic has been addressed.
