### ISSUE TITLE
Dropping a grenade over a railing often fails (fatally)

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#34]
Often when you try to drop a grenade over a railing (eg. Mars City Underground crane area), it fails and drops at your feet instead, killing you.

This is good for when you stick your hand through a solid glass window, but it's bad for sticking your hand over a railing.

**Comment by CarlKenner** [comment]
Fixed in pull request.

**Comment by KozGit** [comment]
I looked at your changes, and saw the comments about getting the shoulder positions, which got me to thinking about the slot implementation as well.

Should we tie the slot positions to joints, ( or offsets to joints ) , instead of the hard coded offsets? Should we change the slot code to reflect the body orientation instead of the view? If so it may be better to just base it off of the player armature. ( Do we want new joints just for the slots? ) 

It wouldn't be too hard to add a routine to poll the world position of player joints by enumerated name if you think that would be useful.

**Comment by CarlKenner** [comment]
The body rotation that the game thinks we have is often something completely implausible, like us facing backwards from where our hands are. Until we fix that, it's probably not worth using it for things like this. I want to redo the IK system eventually, so it detects the difference between leaning forward, moving forward, and looking down. And so the joints don't move into uncomfortable positions. But we should release a version before then.

The slots have to be reachable by the player. So it might not always be good to have them the same position on the model's body. For example, if we're short we might not be able to reach Doomguy's waist. I had to move the slots up from where Leyland had them because they were hard to reach. Eventually, we'll probably want to adjust them programatically based on the player's height.

I like how the slots work when we're not showing the body (except we should probably flip the PDA if it's on the right hip). But I'm not sure what to do when we're showing the body. You can't see the slots past the armour, so it doesn't really matter, but I feel like we should probably use the body's orientation, at least for drawing them.

**Comment by CarlKenner** [comment]
By the way, this bug should also affect firing guns down over railings, but when I test it it usually works.  I'm not sure why. Sometimes I can get it to hit inside the railing when I'm aiming outside, but it's uncommon.
