### ISSUE TITLE
Laser sight comes out of barrel, not laser emitter

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#37]
The pistol has an obvious laser sight emitter below the barrel. You would expect the laser beam or laser dot to come out of there, while the bullets come out of the barrel.

You could make it high tech, and have the laser still aim at the same target, but I would make it low tech and have the laser come out parallel to the barrel and be an inch below the target. Or you could make it somewhere in between and have the laser sight angled up slightly to assume an aim distance.

I'm not sure about the other weapon models.

There should also be an option to only have a laser sight on weapons whose models feature a laser sight, and an option to disable the laser sight completely and just use iron sights.

And you should be able to have both a laser beam and a laser dot.

**Comment by KozGit** [comment]
I can hack in support for this, but to do it the right way, I should really edit the weapon models to add a joint for the laser sight emitter, just like there is a joint for the barrel.  I should probably joints for flashlight attachers as well, instead of hacking it in code like it is now.

I know we've talked about some other things like adding support for two handed weapons and manual reloading.  I can start working on some of this, but I would like to try to identify everything we may want to do that will require changing the models and anims before starting, I'm kind of slow with blender and would like to only have to edit the models and anims once if possible, instead of changing all the anims every time something new is added.

**Comment by KozGit** [comment]
Is the option to have the laser dot and beam visible at the same time intended to help with teleport aiming?

I'm working on some new teleport targets/indicators unrelated to the weapon sights, not sure if this was related.

**Comment by CarlKenner** [comment]
Also, just to look better. Other games that have laser beams have a dot at the end of the beam, and so does SteamVR itself.

**Comment by KozGit** [comment]
Ok, I added the option to use offsets defined in the weapon def files ( vec3 laserSightOffset ), which will be added to the default laser sight origin if vr_laserSightUseOffset is true. 

I updated the .def for pistol, shotgun, supershotgun, machinegun, chaingun, plasmgun, rocket launcher, bfg and grabber to include offsets so the sight will originate from the 'emitter' - let me know if you want to change any of these locations.

Added the option ( updated in menu as well ) to disable the weapon sight, or use beam + dot, beam + circle, or beam + crosshair.

If you think the 'emitter' locations are good, let me know and I'll close the issue.

**Comment by CarlKenner** [comment]
Doesn't it break all saved games when you mess with the def files?
I know I'm trying to load games from other mods, but it's impossible to do that properly because I can't recreate the script states back how they were because it doesn't save the name of variables or functions, just their numbers.
I have to call the constructors on every object again to put them in a sane state, but that's not the state they were in before.

**Comment by KozGit** [comment]
I don't believe so - ( in this case in particular ) I'm not specifically saving this key or offset value in the save game file.  When a weapon def is loaded ( which happens every time the weapon is changed ) the key is scanned for in the weapon def, and if it's found the offset is set. If the def has been archived in a save game, the key just doesn't exist, and the offset will default to 0.  I tested this with a savegame from the previous version with no issues - you may want to test as well as you are more familiar with the save game, but I think we should be good.

This is just my opinion, but if loading from a different mod ( rbdoom, vanilla etc)  I would be fine with ( having an option to? defaulting to ?) just maintaining the difficulty, inventory & health and starting the level at the beginning with a warning message vs having odd failure modes.  

You've done amazing work, but it seems like some savegames will always be incompatible due to the way they were just dumped, like you said.

Even if we forget about the hidef mod, our scripts and defs have already changed to support binding the viewweapon to the model, the model actually having fingers which pose based on the viewmodel, and motion controlling some of the weapons like grenades - so we're always going to be different from vanilla.

(I'm looking at the issue with the player head from the savegames now)

**Comment by CarlKenner** [comment]
But if it becomes a variable in a scriptObject object for the weapon then it will be saved and loaded. I detect when scriptObjects change size in the file, so it doesn't crash, but it may have to invalidate all script objects. I'm not saying it does become a variable in the scriptObject, I haven't checked that yet. But it's something I need to check. It prints out a warning to the console if that happens.

"Loading from a different mod" includes loading our own 015 saves, loading from our own mod when they installed or removed the texture pack, etc. That doesn't cause the backwards head, but it does cause the script issues that can occasionally make a map impossible to complete.

The difficulty, inventory & health are loaded near the end of the loading process. It required a lot of hackery to get the loading process that far without crashing, but that mostly produced a playable map.

I added the restartMap console command so users can do what you suggested. But I can probably find a way to do that automatically, if that's what people want. It seems a shame though if they save near the end after a long map. I think we should display a dialog after loading, warning them and giving them the option of restarting the map, and telling them about the restartMap and endLevel commands.

The player head issue is going to be fixable, it doesn't stop the map from being playable and winnable, and we can always just hide the head if we can't fix it. There's also a slight issue with the weapon, but I fix that by changing weapons after loading from a non-Fully-Possessed savegame.

**Comment by CarlKenner** [comment]
Correction: The bink videos were user error on my part. I accidentally removed them while trying to remove the texture pack. False alarm.

**Comment by KozGit** [comment]
> The rocket launcher has a beam but no dot, unlike the other weapons.
I can't recreate this - are you playing a save game? ( or is this still happening? what happens if you cycle through the weapon sight options?)

> Also, I wasn't sure if the laser on the machine gun should come out of the red light near the top. But using the bottom barrel makes sense, since that never has a muzzle flash, and it makes for more accurate aiming, so I don't mind.

You know its funny,  I did a _ton_ of work on the weapon models and anims, and I never noticed that red spot on the machine gun until you mentioned it.

I'm happy to change the locations of the beam if you like, the spot I chose were just off the cuff to test the offset code.

**Comment by CarlKenner** [comment]
To recreate this bug, just turn OFF sight to surface.

**Comment by KozGit** [comment]
Fixed the reticles not showing up when using the rocket launcher or super shotgun.  You need to install the updated vr.mtr file in the Fully Possessed/materials directory for this to take effect.
