### ISSUE TITLE
Head Bobbing

### ISSUE THREAD

**Issue by KozGit** [KozGit/DOOM-3-BFG-VR#46]
Recent code changes disabled the addition of the viewBob delta in GetViewPosVR unless knockbacks are enabled.

This had the side effect of eliminating vertical smoothing on transitions over steps/bumps, which can be very jarring. 

I've temporarily eliminated the check for knockbacks here so going up/down steps will be smooth again.

In the meantime, normal walk/run headbobs can be ( and I think currently are)  eliminated with the pm_walkbob, pm_runbob etc cvars until we can implement something better.

**Comment by CarlKenner** [comment]
Isn't jarring what we want? Or as I call it, "comfort mode" and "teleporting". I've been trying to make everything as jarring as possible, until there is zero smooth movement anywhere. Zero smooth movement should mean zero motion sickness (now that I've fixed the 45FPS tracking and loading screens).

But the thing I was really trying to get rid of was the huge vertical bounce when landing after jumping. My Motion Sickness Fix code kicks in after ANY physics based movement or eye height changes, EXCEPT this view bobbing. Not only did this motion happen when it shouldn't, it also wasn't being blacked out. So I did this slightly hacky quick fix to disable it.

The reason I used the knockbacks variable was because the comfort and safety protocols menu was full, so I couldn't add another option. In hindsight, I should have merged the knockbacks and headkicks into a single menu option with 4 choices (but setting 2 cvars), rather than 2 options with 2 choices each.

I guess I'll fix my motion sickness detection to respond to head bobs, and use a new cvar for disabling this viewBob.

Do you want a single cvar for both steps/bumps and landing after jumps? Or should they be separate cvars?

**Comment by KozGit** [comment]
Maybe separate cvars?   FWIW, a few versions ago, I had done the same thing, completely eliminating the smooth vertical transitions on steps, and received an overwhelmingly negative response, ( You know how the internet can be ) - so I think it would be good to have an option here.  Sorry, not trying to cause extra work.

To be honest, I can't really say I noticed the bounce after jumping, - its great having a second pair of eyes to pick up on this stuff, ( and its interesting the different things different people pick up on ) so however you want to handle it is good with me.

 The menu limitations are beginning to annoy the heck out of me.  I need to dig into how the scrolling menu is implemented for the key bindings so we can make longer menus for these type of selections, but haven't gotten to it yet.

**Comment by KozGit** [comment]
Fixed - options added for smooth or abrupt steps.
