### ISSUE TITLE
voice commands + main menu not working

### ISSUE THREAD

**Issue by Flubberguts** [KozGit/DOOM-3-BFG-VR#77]
holy shit this is frustrating ive been screaming my head off with voice commands for the past hour how do i get them working they worked for me before i updated my game with the latest update. and how do i open main menu once ive recieved the PDA i can only open it before i recieve it.

**Comment by KozGit** [comment]
There has been no.release yet that supports voice commands. What version are you running ?

**Comment by Flubberguts** [comment]
hmm thats wierd before the last updates 20-21 hours ago i was able to use voice commands, not sure wat version im running the one before those most recent update. also i started blackscreening once i got to the first load screen to the surface dunno why this most recent update killed my game oh well ill prolly wait for release now i guess... sad ones :( lol. also would u be able to fix that black screen at the start menu for release im guessing its because of my radeon card from reading the first few issue posts.

**Comment by KozGit** [comment]
Hi, going to close this issue, voice commands should be working in latest build.  If you're having issues, it may be because cvars changed and differ from whats in your profile, if you try either deleting you profile or save games it may help.

If starting with a clean build and no save still causes this problem, please open a new issue!

Thx
