### ISSUE TITLE
Can you please recreate the Touchpad movement of Onward in this mod ? 

### ISSUE THREAD

**Issue by Jake762x51** [KozGit/DOOM-3-BFG-VR#95]
First of all, touchpad/touchstick makes a few people sick  and that is a big problem, BUT if you do it the right way you can minimise that issue. The good thing is Onward, out of all games, has done the best job of just doing this. Many people who haven't played Onward are always eager to play it off, but the way the movement system in Onward works is undoubtedly the way to go. This was even admitted by Valve themselves : https://youtu.be/kMpQWSqQFK0?t=35m42s

So please please please, get into Onward and try to recreate it's movement system 1 to 1 for this mod.

**Comment by CarlKenner** [comment]
I've never heard of Onward except from Samson's comments in the readme.

**Comment by CarlKenner** [comment]
I just watched this video: https://www.youtube.com/watch?v=YWtAwGeA_ds

Onward style movement is the default in our mod, so I'm not sure what your issue is. We're using third person motion sickness aid, but you can change that in Settings > VR Options > Comfort + Safety Protocols.

We also have Onward-style holstering weapons on your body.

**Comment by KozGit** [comment]
Closing issue, controller relative movement is implemented as default, and with no further info this appears to be addressed.
